name: win-cross-compile

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and Cross Compile
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .env file
        run: echo "DEEPL_API_KEY={{ secrets.DEEPL_API_KEY }}" >> .env
      
      - name: Run tests before compiling
        run: cargo test --all

      - name: Build cross-compile container
        run: docker build . -t gtkrs-crosscomp
        
      - name: Cross compile the application
        run: |
          chmod +x cross_compile.sh
          ./cross_compile.sh
