name: unit-testing

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    build:
        name: Build and Cross Compile
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install gtk dep
              run: sudo apt-get install libgtk-3-dev 

            - name: Setup .env file
              run: echo "DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }}" >> .env

            - name: Run tests
              run: cargo test --all

